#!/bin/bash
# Creates this demo's xMB service and its Application/Pull session through the portal,
# then activates it, which is what actually starts the broadcast: the BM-SC constructs a
# FLUTE Transmitter, fetches the manifest from the local origin, FLUTE-delivers the
# presentation, and the MBMS-GW sets up the bearer.
#
# It writes the session definition to run/state/ first, in the same template format the
# portal's own "Load template..." button and demo-content/load-demo.js accept, so the
# exact session this script provisions can also be loaded by hand from the UI.
#
# Inputs are all in env.sh: the TMGI/TSI/C-TEID identity, the multicast address, and
# which presentation on the local origin is the entry point.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
source env.sh
source lib.sh
ensure_dirs

require_cmd curl
require_cmd python3
portal_creds

PRESENTATION="$(live_presentation_path)"
ENTRY_POINT="http://$MEDIA_HOST:$MEDIA_PORT/$PRESENTATION"
MIME="$(live_presentation_mime)"
# Named after the presentation, because start-all.sh calls this once per on-air channel.
TEMPLATE="$STATE_DIR/local-live-$LIVE_STREAM_NAME.json"

# The origin must already be serving the presentation: the BM-SC's Pull ingest resolves
# the segment list from the manifest at activation, so activating against a manifest that
# is not there yet produces a session that looks healthy and delivers nothing.
curl -s -o /dev/null -m 5 "$ENTRY_POINT" \
    || die "the entry point $ENTRY_POINT is not being served; run ./02-start-media-server.sh first"

cat > "$TEMPLATE" <<JSON
{
  "description": "Local live demo: broadcasts the looping $LIVE_FORMAT presentation published by this demo's own origin (media-server.js on $MEDIA_HOST:$MEDIA_PORT) over MBMS, via an xMB Application/Pull session. Generated by 04-provision-live-service.sh from env.sh; edit env.sh, not this file.",

  "service": {
    "serviceClass": "$DEMO_SERVICE_CLASS",
    "serviceNames": ["$DEMO_SERVICE_NAME"],
    "serviceLanguages": ["$DEMO_SERVICE_LANG"],
    "receiveOnlyMode": true,
    "serviceAnnouncementMode": "SACH"
  },

  "sessions": [
    {
      "sessionType": "Application",
      "maxBitrate": $DEMO_MAX_BITRATE,
      "fecEnabled": $DEMO_FEC_ENABLED,

      "mbmsBearer": {
        "tmgiMcc": "$DEMO_TMGI_MCC",
        "tmgiMnc": "$DEMO_TMGI_MNC",
        "tmgiServiceId": $DEMO_TMGI_SERVICE_ID,
        "mcastAddr": "$DEMO_MCAST_ADDR",
        "port": $DEMO_MCAST_PORT,
        "tsi": $DEMO_TSI,
        "serviceAreaCode": $DEMO_SERVICE_AREA_CODE,
        "cTeid": $DEMO_C_TEID,
        "mmeSmPeers": "$DEMO_MME_SM_PEERS"
      },

      "application": {
        "ingestMode": "Pull",
        "applicationEntryPointURL": "$ENTRY_POINT",
        "applicationServiceDescription": "$MIME"
      }
    }
  ]
}
JSON
log "session definition written to $TEMPLATE"

svc_body=$(python3 -c 'import json,sys; print(json.dumps(json.load(open(sys.argv[1]))["service"]))' "$TEMPLATE")
sess_body=$(python3 -c 'import json,sys; print(json.dumps(json.load(open(sys.argv[1]))["sessions"][0]))' "$TEMPLATE")

log "creating the xMB service"
svc_id=$(portal_post_for_id "service creation" "/api/xmb/services" "$svc_body")
echo "$svc_id" > "$STATE_DIR/service_id"
log "service: $svc_id"

log "creating the Application/Pull session (entry point $ENTRY_POINT)"
sess_id=$(portal_post_for_id "session creation" "/api/xmb/services/$svc_id/sessions" "$sess_body")
echo "$sess_id" > "$STATE_DIR/session_id"
log "session: $sess_id"

# Activate by PUTting the session back with state Active, which is exactly what the
# portal's own Activate button does. The session is read back first so the PUT carries
# the server's own view of it and not just the fields this script sent.
current=$(portal_api GET "/api/xmb/services/$svc_id/sessions/$sess_id")
activate_body=$(python3 - "$sess_body" <<'PY'
import json, sys
sent = json.loads(sys.argv[1])
current = sys.stdin.read().strip()
body = dict(sent)
try:
    got = json.loads(current)
    if isinstance(got, dict):
        # The portal wraps the session as {ok: true, ...session} on some routes.
        got.pop("ok", None)
        if got:
            body = {**got, **{k: v for k, v in sent.items() if k not in got}}
except Exception:
    pass
body["state"] = "Active"
print(json.dumps(body))
PY
<<<"$current")

log "activating the session (the BM-SC fetches the manifest here, which can take 10-30s)"
resp=$(portal_api PUT "/api/xmb/services/$svc_id/sessions/$sess_id" "$activate_body")
if ! grep -q '"ok"[[:space:]]*:[[:space:]]*true' <<<"$resp"; then
    die "activation failed: ${resp:-no response}
  A session left over from a previous run is the usual cause. See the tutorial's
  DEMO_RUNBOOK.md (\"xMB activation rejected as already active\"): a full transmit-side
  restart is the reliable fix, not a repeated activate."
fi

log "session active. Content is now being FLUTE-delivered over the bearer."
log "  player UI : http://$RX_ADDR:$APP_PORT"
log "  portal    : $PORTAL_URL  (xMB tab shows the service and session)"
