services:
  mbms-modem:
    build:
      context: ./
      dockerfile: Dockerfile-MBMS-Modem
    ports:
      - "3010:3010"
    volumes:
      - ./config/5gmag-rt.conf:/etc/config/5gmag-rt.conf
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
      - /var/run/smcroute.sock:/var/run/smcroute.sock
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
#  mbms-mw:
#    build:
#      context: ./
#      dockerfile: Dockerfile-MBMS-MW
#    ports:
#      - "3020:3020"
#    volumes:
#      - ./config/5gmag-rt.conf:/etc/config/5gmag-rt.conf
#    depends_on:
#      - mbms-modem
#  mbms-wui:
#    build:
#      context: ./
#      dockerfile: Dockerfile-MBMS-WUI
#    ports:
#      - "8000:80"
#    depends_on:
#      - mbms-modem
#      - mbms-mw
