# Stage 1: Build Node.js app
FROM node:20 AS builder
WORKDIR /opt/rt-wui
RUN git clone https://github.com/5G-MAG/rt-wui.git . && npm install && npm run build

# Stage 2: Use nginx image
FROM nginx:latest
COPY --from=builder /opt/rt-wui/build /usr/share/nginx/html
COPY 5gmag-rt-wui.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]