[mbms_gw]
sgi_mb_tun_enable = 0
sgi_mb_if_name = sgi_mb
sgi_mb_if_addr = 172.16.1.1
sgi_mb_if_mask = 255.255.255.255
m1u_multi_addr = 239.255.0.1
m1u_multi_if = 127.0.1.200
m1u_multi_ttl = 1
[mbms_gw_sm]
sm_bind_addr = 0.0.0.0
sm_bind_port = 0
[control]
bind_addr = 127.0.0.1
port = 2101
[sgi_mb_tunnel]
enable = 1
bind_addr = 127.0.0.1
bind_port = 47000
[log]
all_level = debug
filename = stdout
